### ISSUE TITLE
Current Tree Walk causes evaluation damage

### ISSUE THREAD

**Issue by dougfoster-email** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#113]
Current DMARC policies are configured based on RFC7489 and the PSL, and evaluators obtain results based on those implementation decisions.   Domain owners may have many reasons to want an alternative to the PSL:  (1) The PSL may contain errors that impact the domain owner's mail flow.  (2) The PSL is implemented in different iterations by different evaluators.   (3) The RFC7489 / PSL algorithm does not allow for partitioned alignment within an organization.  Nonetheless, an evaluator has no justification for implementing an algorithm which produces different results unless the domain owner indicates that he prefers usage of that different algorithm.    This can be accomplished by tagging his DMARC policies to indicate which of the four possible roles applies to a particular policy:   Org Top, Subdomain, Org Top-and-Bottom (single label registry), and Org Bottom (bottom layer of a multiple-layer private registry), and DMARCbis should define those tags   The current upward-walk proposal will cause damage by directing evaluators to apply an undesired and often incorrect re-interpretation of domain owner intent and associated alignment boundaries.

**Comment by toddherr** [comment]
Closing per chair's instruction.
