### ISSUE TITLE
editorial nits in section 5.3

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#117]
In section   5.3.  General Record Format

Note the following:

     adkim:  (plain-text; OPTIONAL; default is "r".)  Indicates whether

     aspf:  (plain-text; OPTIONAL; default is "r".)  Indicates whether the

The period is before the parenthesis.

**Comment by jrlevine** [comment]
See sections 6.13 and 6.98 of the Chicago Manual of Style. There's a lot of history in this nit.

**Comment by moonshiner** [comment]
Agreed.  What I was going to say but hit submit too fast was "these are different than the others in how they place these).

I leave the style nits to the masters
