### ISSUE TITLE
Some Spelling Nits

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#125]
5.5.2

   messages sent to such users will always produce DMARC fail.

always produce DMARC failure ? 

5.8

	However, such deviation is not proscribed.

While proscribed is correct, perhaps something like allowed be more obvious 
to non-English speakers?

8.6
   without further anaysis is that rejecting messages that have been

s/anaysis/analysis/

   subscriptions to that mailing list cancelled by the list software's

s/cancelled/canceled/

10.1

   organizational PSDs that do not mandate DMARC use by registants risk

s/registants/registrants/

**Comment by toddherr** [comment]
5.5.2 changed to 'DMARC result of "fail"' in keeping with other uses of that phrasing in the document.

5.8 changed 'proscribed' to 'forbidden'.

8.6 changed to 'analysis' and 'canceled', respectively.

10.1 changed to 'registrants'

**Comment by toddherr** [comment]
Changes incorporated into rev -31 branch.

Closing issue.
