### ISSUE TITLE
DMARCbis WGLC: Description of psd=n

### ISSUE THREAD

**Issue by toddherr** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#126]
As posted on list by Ale Vesely:

`Section 5.3, in the format description of psd:

       n:  The DMARC policy record is published for a PSD, but it is the
          Organizational Domain for itself and its subdomain.  There is
          no need to put psd=n in a DMARC record, except in the very
          unusual case of a parent PSD publishing a DMARC record without
          the requisite psd=y tag.

Perhaps a "not" is missing between "is" and "published"?  I'd just say the 
domain is not a PSD /and/ it is the Organizational Domain for itself and 
its subdomain.`

**Comment by jrlevine** [comment]
Right, there's a missing 'not'

but it is not the Organizational Domain for itself or its subdomains.

**Comment by toddherr** [comment]
Change made and pushed to committed branch (rev-31)

**Comment by toddherr** [comment]
Reopening as there's still discussion occurring on-list

**Comment by toddherr** [comment]
Discussion ended; text now reflects consensus as the editor understands it.
