### ISSUE TITLE
DMARCbis WGLC: 9.5 DMARC Report Format Registry

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#130]
with this being actually now historic, I suggest the text be updated to reflect this registry was created in 7489 but the whole thing is deprecated

I can suggest text if need be

**Comment by toddherr** [comment]
@moonshiner I will take you up on your offer to suggest text here.

**Comment by toddherr** [comment]
No suggested text offered, and not entirely clear on meaning of this ticket, as afrf doesn't seem to be 'historic' per https://www.iana.org/assignments/dmarc-parameters/dmarc-parameters.xhtml.

Closing ticket but will entertain arguments to reopen.

**Comment by alevesely** [comment]
And why would this be (or have been) an issue of DMARCbis rather than failure-reporting?
