### ISSUE TITLE
DMARCbis WGLC: 9.2.  Authentication-Results Result Registry Update

### ISSUE THREAD

**Issue by moonshiner** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#131]
The additions to the IANA registry in the document doesn't match the existing registry

I feel the columns should be reordered or the text should like section 9.3

I have some examples here

https://gist.github.com/moonshiner/76dd5ff22f65b84969716ff09be1ac1a

**Comment by toddherr** [comment]
Tables in section 9.1 and 9.2 now match the existing IANA registry

Updates have been pushed to working branch.
