### ISSUE TITLE
RFC 7489 Errata for ietf-dmarc-aggregate-reporting

### ISSUE THREAD

**Issue by toddherr** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#139]
The following RFC 7489 Errata apply, in whole or in part, to ietf-dmarc-aggregate-reporting:

- https://www.rfc-editor.org/errata/eid5365
- https://www.rfc-editor.org/errata/eid5371
- https://www.rfc-editor.org/errata/eid5440 (Section 7.1 bits)
- https://www.rfc-editor.org/errata/eid6439
- https://www.rfc-editor.org/errata/eid6485
- https://www.rfc-editor.org/errata/eid5774

**Comment by abrotman** [comment]
TBD on:

https://www.rfc-editor.org/errata/eid5440 
https://www.rfc-editor.org/errata/eid6485
https://www.rfc-editor.org/errata/eid5774

**Comment by abrotman** [comment]
Seems these are all covered.
