### ISSUE TITLE
AD Review - Amend Tree Walk So To Handle psd=y On First Query?

### ISSUE THREAD

**Issue by toddherr** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#156]
The DNS Tree Walk described in Section 4.10 of [DMARCbis rev -34](https://www.ietf.org/archive/id/draft-ietf-dmarc-dmarcbis-34.html) lists the first two steps of a generic tree walk as follows:

> 1. Query the DNS for a TXT record that matches the format of a DMARC Policy Record at
>    the starting point for the Tree Walk.  The starting point for the DNS Tree Walk will
>    depend on the ultimate target of the DNS Tree Walk. (#dmarc-policy-discovery) and
>    (#identifier-alignment-evaluation) describe the possible starting points. A possibly
>    empty set of records is returned.
>
> 2. Records that do not start with a "v" tag that identifies the current
>     version of DMARC are discarded. If multiple DMARC Policy Records are
>     returned, they are all discarded. If a single record remains and it
>     contains a "psd=n" tag, stop.

Step 6 in that same generic tree walk reads:

> 6. Records that do not start with a "v" tag that identifies the current
>     version of DMARC are discarded. If multiple DMARC Policy Records are returned for
>.    a single target, they are all discarded. If a single record remains and it
>.    contains a "psd=n" or "psd=y" tag, stop.

Because step 2 says nothing about what to do with records containing "psd=y" at that step, the potential exists for there to be two records remaining, found at different names, after step 6, with one containing "psd=y" and the other "psd=n".

Should the tree walk be amended, specifically step 2, to end with

> If a single record remains and it contains a "psd=n" tag or a "psd=y" tag, stop.

If not, what should be done to prevent this possible issue with two records and two different psd tags?

**Comment by Daniel-t** [comment]
Agreed, implemented as written could result in a bad outcome for our 3rd level PSD (which will have psd=y soon).  If our parent domain (also a PSD) implements a DMARC policy without psd=y.  Then according to 4.10.2, the parents (fewest number of labels) DMARC policy would be chosen over ours. 

This "If a single record remains and it contains a "psd=n" tag or a "psd=y" tag, stop." appears to resolve the issue. 
Alternatively change point 2 in 4.10.2, however this would be more complicated to specify.

**Comment by alevesely** [comment]
When you find psd=y, the org domain is the domain found at the previous iteration.  At step 2 there is no previous iteration, so it makes no sense to stop there.

If the parent domain is a PSD which doesn't publish psd=y, you need to publish psd=n.  If you yourself are a PSD, all your subdomains then have to publish psd=n as well.

**Comment by Daniel-t** [comment]
Our scenario is a PSD, which is a child of a PSD.  Our immediate parent doesn't yet publish a DMARC policy however hopefully will in the not too distant future though,  I can't guarantee that they will implement psd=y when they do.   There are about 250 PSDs in the publicsuffix.org list which will be in a similar situation to ourselves.

If we (a PSD) publish psd=n, we'd override all of our sub-domains DMARC policies (all controlled by separate organisations) until they update their own to include psd=n.  This would be a nightmare scenario for us.

If we dont publish psd at all, we'll still override the sub-domain policies (shortest number of tags) until they add psd=n. Again a bad outcome. 

Our only option with the new discovery process is psd=y, as this will cause the existing sub-domain policies to be respected as is, while providing a policy for our top level domain and the children which dont have a policy for themselves. 

There needs to be a way for legitimate emails coming from a PSD (with psd=y) to be handled.  The easiest way is as proposed by @toddherr above and accept that when the first query returns psd=y it is the organisational domain.

**Comment by toddherr** [comment]
Amended step 2 to say stop if psd=y or psd=n found, and pushed in rev -36

**Comment by matteocontrini** [comment]
> If we (a PSD) publish psd=n, we'd override all of our sub-domains DMARC policies (all controlled by separate organisations) until they update their own to include psd=n. This would be a nightmare scenario for us.
> 
> If we dont publish psd at all, we'll still override the sub-domain policies (shortest number of tags) until they add psd=n. Again a bad outcome.

Apologies if I missed something, but could you clarify where this interpretation comes from?

The policy discovery is described in section 4.10.1 and it currently says:

>The DMARC Policy Record to be applied to an email message will be the record found at any of the following locations, listed from highest preference to lowest:
>* The Author Domain
>* The Organizational Domain of the Author Domain
>* The Public Suffix Domain of the Author Domain

So if you set `psd`, the Author Domain will still have priority and your Publix Suffix Domain won't override subdomains policies.

If you don't explicitly set `psd` to `y` or `n` on a domain (to mark it as PSD or Organizational), that policy will be ignored altogether and won't override anything, or at least that's what the above text appears to say.

Also, you mentioned section 4.10.2 but that section specifies how to determine the Organizational Domain for alignment checks, and not how to discover the Policy Domain, which is instead specified in 4.10.1. So for example the part about the "smallest number of labels" doesn't apply to policy discovery.

---

**EDIT:** I've read it again and I noticed the part where the definition of Organizational Domain refers to 4.10.2. So this was my mistake in interpreting the whole thing, sorry for the noise.

(To be honest the fact that part of the policy discovery is defined in a section that is titled "Identifier Alignment Evaluation" is a bit confusing.)

**Comment by jrlevine** [comment]
Daniel is mistaken. If a domain has a DMARC record, that policy applies. The org and PSD policies are fallbacks for domains with no policies of their own.
