### ISSUE TITLE
Define "cousin domains"

### ISSUE THREAD

**Issue by toddherr** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#167]
and perhaps "lookalike domains"?

See [post](https://mailarchive.ietf.org/arch/msg/dmarc/ABSjuJ3ADsTPkKGba-OBsupRmaY/)

**Comment by d-javu** [comment]
Mail to the list repeated:

In the Anti-Phishing section referred to it is written:

```... visually similar domain names ("cousin domains")```

which indicates, at least to me, that this is the definition.

It is not used again in that document, but "cousin domains" is used
twice in Aggregate Reporting, and it looks like it can be easily removed
from there, as it does not clarify anything the term "typo domains", or
similar would not do better.

I think the parenthesized ("cousin domains") can be safely removed from
dmarcbis.

aggregate-reporting, can fix it by calling it typo domains, or something.

I do not think "typo domain" needs a definition.

In aggregate reporting, "cousin domains" is mentioned in the context of
risk of feedback leakage to a PSO, and require a few unlikely things to
occur.

* The sender must mis-configure the RFC5322.From to contain a non-existent domain name.
* The Mail Receiver must accept mail with said non-existent domain name.
* The aggregate report must be sent to the PSO.

**Comment by jrlevine** [comment]
Agree, cousin domains just confuse things in this spec.

**Comment by toddherr** [comment]
Addressed in this commit - b7a00a39e645e64f5674065d5cc297461fa71097
