### ISSUE TITLE
Section 4.7, Update rua and ruf tag descriptions

### ISSUE THREAD

**Issue by toddherr** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#169]
Both tag descriptions contain the sentence:

> A Mail Receiver MUST implement support for a "mailto:" URI, i.e., the ability to send a DMARC report via electronic mail.

These should be conditional, not absolute, e.g.,

> A Mail Receiver that fully participates in DMARC MUST implement support for a "mailto:" URI, i.e., the ability to send a DMARC report via electronic mail.

**Comment by alevesely** [comment]
I agree, albeit that change makes those already longish definitions longer.

Couldn't we say it without MUSTard, for example like so:

OLD
>  Any valid URI can be specified. A Mail Receiver MUST implement support for a "mailto:" URI, i.e., the ability to send a DMARC report via electronic mail.

NEW
>  Any valid URI can be specified, but only the "mailto:" URI, i.e. the ability to send a DMARC report via electronic mail is supported.

**Comment by kivinen** [comment]
If you have MUST with condition it is SHOULD. The original text is fine, it says mailto is mandatory to implement (not to use). On the other hand nothing says anywhere that sending reports is mandatory so if you do not implement sending reports at all, then implementing "not sending reports" using mailto happens automatically...

In standard track document we need to have features that interoperate. Usually that means we need to pick at least one mandatory to implement option. In this case the MANDATORY (or MUST) feature is mailto uri.

**Comment by toddherr** [comment]
Text clarified in this commit - 72408af29057bdd47a1e76c09501d541dcc722b9
