### ISSUE TITLE
Proposed Update to Section 7.4, Interoperability Considerations

### ISSUE THREAD

**Issue by toddherr** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#170]
Based on [this message](https://mailarchive.ietf.org/arch/msg/dmarc/Y7b8MAD_hoE4iul7sScIvtZd25c/) the following text update is presented for consideration by the working group, with an on-list consensus decision sought.

The proposal is to change the following paragraph in section 7.4:

> It is therefore critical that Mail Receivers MUST NOT reject incoming messages solely on the basis of a "p=reject" 
> policy by the sending domain. Mail Receivers must use the DMARC policy as part of their disposition decision, 
> along with other knowledge and analysis. "Other knowledge and analysis" here might refer to observed sending 
> patterns for properly-authenticated mail using the sending domain, content filtering, etc. In the absence of other 
> knowledge and analysis, Mail Receivers MUST treat such failing mail as if the policy were "p=quarantine" rather 
> than "p=reject".

To read as follows:

> It is therefore critical that Mail Receivers SHOULD NOT reject incoming messages solely on the basis of a "p=reject" 
> policy by the sending domain. Mail Receivers SHOULD use the DMARC policy as part of their disposition decision, 
> along with other knowledge and analysis. "Other knowledge and analysis" here might refer to observed sending 
> patterns for properly-authenticated mail using the sending domain, content filtering, etc. In the absence of other 
> knowledge and analysis, Mail Receivers SHOULD treat such failing mail as if the policy were "p=quarantine" rather 
> than "p=reject".

**Comment by alevesely** [comment]
No for the first MUST NOT->SHOULD NOT.  In fact, SHOULD NOT implies that in some cases you do reject it.  What cases?  Obviously cases in which you have other knowledge.  Thus the meaning is actually the same, but MUST NOT is sharper and better satisfactory to purists —in fact, blindly rejecting precludes interoperability (for the time being).

**Comment by kivinen** [comment]
I think the first MUST NOT->SHOULD NOT change is wrong, and it should be kept as MUST NOT. The changing from "must" to "SHOULD" is fine, and I can accept the final change from "MUST treat" to "SHOULD treat", even when I would be more happy with the original MUST version.

**Comment by toddherr** [comment]
No consensus reached for proposed change. Closing.
