### ISSUE TITLE
Proposed Update - Removal Any Conditional Language in DMARCbis

### ISSUE THREAD

**Issue by toddherr** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#171]
Several posts in [this thread](https://mailarchive.ietf.org/arch/msg/dmarc/0_FfUyvkORacYypclQi009jGKzo/) contain a request that any reference to "participating in DMARC" be removed. 

An example is found in [this message](https://mailarchive.ietf.org/arch/msg/dmarc/022i0yFgLAppCGQynkyYbvH6B5c/):

> changing 5.3.7 from:
> 
> ----------------------------------------------------------------------
> 5.3.7.  Store Results of DMARC Processing
> 
>    If the Mail Receiver intends to fully participate in DMARC, then
>    results obtained from the application of the DMARC mechanism by the
>    Mail Receiver MUST be stored for eventual presentation back to the
>    Domain Owner in the form of aggregate feedback reports.  Section 4.7
>    and [I-D.ietf-dmarc-aggregate-reporting] discuss aggregate feedback.
> ----------------------------------------------------------------------
> 
> to
> 
> ----------------------------------------------------------------------
> 5.3.7.  Store Results of DMARC Processing
> 
>    The results obtained from the application of the DMARC mechanism by
>    the Mail Receiver SHOULD be stored for eventual presentation back
>    to the Domain Owner in the form of aggregate feedback reports.
>    Section 4.7 and [I-D.ietf-dmarc-aggregate-reporting] discuss
>    aggregate feedback.
> ----------------------------------------------------------------------
> 

This issue is being opened in an effort to seek on-list consensus for this requested change.

**Comment by r65536** [comment]
One way forward would be a rubric at the beginning that said there were various aspects of participation in DMARC and that (some specified parts of?) the document was written in sections that covered each type of participation. It is common for both Mail Sender and Receivers to ignore some aspects of DMARC altogether, for example, not sending reports. For clarity there are no conditionals within those sections -- however those not choosing to participate in a particular aspect of DMARC can ignore that section and any RFC2119 language within it.

**Comment by alevesely** [comment]
*If x then MUST* and *SHOULD* are formally the same.  However, the former clarifies the condition and thus is clearer.  Adding the consideration that it is also the current text, I'd opt for not changing.

The conformance question seems to have been roughly opposed.

**Comment by kivinen** [comment]
Unless we define what "fully participate" is supposed to mean, i.e., if we do have multiple levels of DMARC, one which "fully participates", one which "partially participates", and we defined requirements for all of those, I think we need to get rid of those terms which are not defined anywhere.

They are not helping anybody. If you think some feature is only needed by some of the implementations it is MAY, if you think it should be recommended to implement, then it is SHOULD, if everybody needs to do it it is MUST. 

And I still think we DO need to collect requirements in one place, and clearly define what features of the DMARC are mandatory to implement, and which are optional.

**Comment by r65536** [comment]
<quote>f you think some feature is only needed by some of the implementations it is MAY, if you think it should be recommended to implement, then it is SHOULD, if everybody needs to do it it is MUST.</quote>

That's not what RFC2119 says the definitions of those words are

**Comment by jrlevine** [comment]
The whole bit about what it means to participate is really marketing, not interop, so I would take out all of the 2119 words.

**Comment by kivinen** [comment]
> f you think some feature is only needed by some of the implementations it is MAY, if you think it should be recommended to implement, then it is SHOULD, if everybody needs to do it it is MUST.
> 
> That's not what RFC2119 says the definitions of those words are

That is my reading of the RFC2119. 

RFC2119 says:

1. MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification.

Meaning it is absolute requirement, and you need to do all MUSTs that are listed in the specification. 

As for SHOULD it says:

3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

So if there is a reason not to implement something then it is SHOULD. 

I would like to know how you think those should be understood. This is how we have been using those words in the security area, which is why we do for example require at least one MUST implement cryptographic algorithm so every implementation MUST support it, and all implementations can be configured to use that to gain interoperability.

Same here, if we do not define at least one authentication method (DKIM, or SPF) as MUST then there will not be interoperability because if sender implements only SPF, and receiver only DKIM they cannot interoperate regardless who they configure things. 

We are talking about the standard track document here, all of this is interoperability, not marketing.  

Having marketing text in the RFC is fine when you are talking about the informational RFC; but when you are talking about standard track RFC, you need to define how different implementations can interoperate with each other.

**Comment by r65536** [comment]
You said that (and I quoted you to avoid misapprehension) "if it was recommended" implied a SHOULD ... and that is what I was saying was incorrect.  If  it goes beyond a recommendation then of course SHOULD can be appropriate.

As to inter-operation. A receiver not sending reports does not cause an interoperation failure. It may be less than ideal in that it may not be what a sender wishes, but it does not prevent the rest of the protocol from working and it does not prevent both the sender and the receiver having a benefit from it.

**Comment by kivinen** [comment]
SHOULD is synonym to recommended, so if something is SHOULD it is recommended to be implemented versus mandatory to implement. I still have no idea what you claim that I was say that was wrong based on the RFC2119. 

You say " If it goes beyond a recommendation then of course SHOULD can be appropriate.", and I do not think it needs to go beyond a recommendation to make it SHOULD. If it is recommended then it is SHOULD. 

It is true that sending reports is not needed for interoperability, so I think it should be SHOULD, as to be able to see that your mail infrastructure is properly adding authentication you need to get reports that say so. If nobody implements reports then people are left in dark whether their systems are working or not. After you have your system up and running then reports gets less and less useful, as there is nothing you can fix if other people generate mails claiming to be from you and they fail authentication. 

As the original text did have "If the Mail Receiver intends to fully participate in DMARC" and then MUST, I said it is not MUST anymore if there is reason not to do it. And I think removing "fully participate" conditional and making it SHOULD is appropriate.

And in total I think this is wrong place to put text which says whether implementing reporting is REQUIRED (MUST) or RECOMMENDED (SHOULD), or just OPTIONAL (MAY). Yes, storing results are needed to implement reports, but even if you store results for later use, that does not yet mean that you are sending reports, it only allows you to sending them. 

We do need the section which lists all the REQUIRED, RECOMMENDED and OPTIONAL features, so implementers do not need to try to parse this kind of text to find out what they need to implement.

**Comment by jrlevine** [comment]
I'm not seeing support for Tero's position from anyone else so I don't think it's worth further argument.

I'm OK with Richard's suggestion that we have a non-normative discussion about what the marketing term "participate" usually means.

**Comment by kivinen** [comment]
I think it is pointless to do IETF standard track document for marketing purposes. We do not need such things in standards. But it seems it is pointless to continue discussing this in here, and it would be better to bring this up to the IESG.

**Comment by toddherr** [comment]
I see no need for a rubric; initial paragraphs in section 5.1 and 5.3 describe what it means for Domain Owners and Mail Receivers to fully participate in DMARC, respectively.

In this commit - aa8646b33cd8b5a0ae08011c0385e314ad14911e - I have removed other mentions of the phrase "fully participate" but preserved the "If you want to achieve X, then you MUST do Y" ethos.
