### ISSUE TITLE
Update rua grammar

### ISSUE THREAD

**Issue by alevesely** [ietf-wg-dmarc/draft-ietf-dmarc-dmarcbis#172]
Daniel K. [proposes](https://mailarchive.ietf.org/arch/msg/dmarc/dmGrR0LF0baI-DKDI0Ig2CsllHM) the following:
```
obs-dmarc-uri = dmarc-uri [ "!" 1*DIGIT [ "k" / "m" / "g" / "t" ] ]
              ; Obsolete syntax, reporters should ignore the
              ; size if it is found in a DMARC Policy Record.

and then update dmarc-urilist with the alternative

dmarc-urilist = ( dmarc-uri *(*WSP "," *WSP dmarc-uri) )
              / ( obs-dmarc-uri *(*WSP "," *WSP obs-dmarc-uri) )
```

**Comment by toddherr** [comment]
Rejected, because the proposed dmarc-urilist does not allow for the possibility of a combination of dmarc-uri and obs-dmarc-uri in the same urilist, and there are too many permutations of such combinations to be practical for listing.
